version: '2'
services:
    shop-app:
        image: shop
        external_links:
            - shop-mysql:mysql
            - shop-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shop?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    shop-mysql:
        extends:
            file: mysql.yml
            service: shop-mysql
    shop-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: shop-elasticsearch
